In [1]:
import numpy as np

In [2]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
matrix = np.zeros((3, 3))
print(matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)


[[7 8 2 7 5]
 [5 3 2 7 2]
 [5 8 7 7 5]
 [5 4 7 4 5]
 [9 7 4 1 5]]


In [7]:
random_matrix = np.random.rand(4, 4).round(2)
print(random_matrix)


[[0.78 0.39 0.07 0.64]
 [0.54 0.72 0.76 0.64]
 [0.31 0.98 0.03 0.2 ]
 [0.05 0.69 0.52 0.03]]


In [10]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

add = array1 + array2
print(add)

sub = array1 - array2
print(sub)

mult = array1 * array2
print(mult)

[12  6  8 16 10]
[ 4 -2  0 -4  2]
[32  8 16 60 24]


In [12]:
vect_first = np.random.random(7)
vect_sec = np.random.random(7)
scalar = np.dot(vect_first, vect_sec).round(2)
print(scalar)

1.57


In [14]:
matrix_first = np.random.randint(1, 11, size=(2, 2))
matrix_sec = np.random.randint(1, 11, size=(2, 3))
result = np.dot(matrix_first, matrix_sec)
print(result)


[[20 70 82]
 [43 56 44]]


In [19]:
matrix = np.random.randint(1, 11, size=(3, 3))
result = np.linalg.inv(matrix).round(3)
print(result)

[[ 0.208 -0.583  0.083]
 [-0.007  0.319 -0.069]
 [-0.09   0.153  0.097]]


In [23]:
matrix = np.random.rand(4, 4)
result = np.transpose(matrix).round(3)
print(result)

[[0.619 0.352 0.399 0.661]
 [0.056 0.66  0.031 0.867]
 [0.231 0.841 0.688 0.387]
 [0.443 0.404 0.816 0.568]]


In [24]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
result = np.dot(matrix, vector)
print(result)

[ 75 184 171]


In [26]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
result = np.dot(matrix, vector).round(3)
print(result)

[0.487 0.984]


In [28]:
matrix_first = np.random.randint(1, 11, size=(2, 2))
matrix_sec = np.random.randint(1, 11, size=(2, 2))
result = np.multiply(matrix_first, matrix_sec)
dot_result = np.dot(matrix_first, matrix_sec)
print(result)
print(dot_result)

[[12 27]
 [60 12]]
[[66 42]
 [78 42]]


In [29]:
matrix = np.random.randint(1, 101, size=(5, 5))
result = np.sum(matrix)
print(result)

1524


In [30]:
matrix_first = np.random.randint(1, 11, size=(4, 4))
matrix_sec = np.random.randint(1, 11, size=(4, 4))
result = np.subtract(matrix_first, matrix_sec)
print(result)

[[-9  6  1  4]
 [-6 -5 -4 -3]
 [-4  4  2  9]
 [ 3  1  1  1]]


In [32]:
matrix = np.random.rand(3, 3)
result = np.sum(matrix, axis=1, keepdims=True).round(3)
print(result)

[[1.924]
 [2.219]
 [0.337]]


In [35]:
matrix = np.random.randint(1, 11, size=(3, 4))
print(matrix)
result = np.square(matrix)
print(result)

[[ 2  5  8  5]
 [ 1  8  1  8]
 [10  2  6  9]]
[[  4  25  64  25]
 [  1  64   1  64]
 [100   4  36  81]]


In [38]:
vector = np.random.randint(1, 51, size=4)
result = np.sqrt(vector).round(2)
print(result)

[4.24 2.83 4.9  4.8 ]
